import * as path from 'path';
import * as vscode from 'vscode';
import { MemoryManager } from '../core/MemoryManager';
import { ContextCompressor } from '../core/ContextCompressor';
import { writeTextFile } from '../utils/fileUtils';
import { SecretRedactor } from '../utils/secretRedactor';

const HEADER = `# ═══════════════════════════════════════════════════════════
# OPTIMIZED AI CONTEXT PROMPT — Generated by Context Optimizer
# Compatible with: ChatGPT, Claude, Gemini, Cursor, Windsurf,
#                  GitHub Copilot, Antigravity, and any LLM
# ═══════════════════════════════════════════════════════════
# INSTRUCTIONS FOR AI:
# Read this context carefully. This is a complete snapshot of
# the project. Use it to understand the codebase without
# needing additional explanation.
# ═══════════════════════════════════════════════════════════

`;

export class PromptExporter {
  constructor(
    private memoryManager: MemoryManager,
    private compressor: ContextCompressor
  ) {}

  /** Export the full, readable optimized prompt (respecting token budget setting) */
  exportFull(): string {
    const mem = this.memoryManager.get();
    const config = vscode.workspace.getConfiguration('contextOptimizer');
    const budget = config.get<number>('tokenBudget', 4000);

    const body = this.compressor.generatePromptUnderBudget(mem, budget);
    const content = HEADER + body;
    const outputPath = path.join(this.memoryManager.getExportsDir(), 'optimized_prompt.txt');
    writeTextFile(outputPath, content);
    return outputPath;
  }

  /** Export the minimized (lowest token) prompt */
  exportMinimized(): string {
    const mem = this.memoryManager.get();
    const content = this.compressor.generateMinimizedPrompt(mem);
    const outputPath = path.join(this.memoryManager.getExportsDir(), 'optimized_prompt.min.txt');
    writeTextFile(outputPath, content);
    return outputPath;
  }

  /** Get prompt formatted for Claude 3.5 & Antigravity (<codebase_context> XML) */
  getClaudePrompt(): string {
    const mem = this.memoryManager.get();
    const body = this.compressor.generateOptimizedPrompt(mem);
    const xml = `<codebase_context project="${mem.project.name}" version="${mem.project.version || '1.0.0'}">\n${body}\n</codebase_context>`;
    return SecretRedactor.sanitize(xml);
  }

  /** Get prompt formatted for ChatGPT System Prompt */
  getChatGPTSystemPrompt(): string {
    const mem = this.memoryManager.get();
    const body = this.compressor.generateOptimizedPrompt(mem);
    const prompt = `System Directive: You are an expert AI software engineer pair programming on project "${mem.project.name}". Refer to the following project context snapshot:\n\n${body}`;
    return SecretRedactor.sanitize(prompt);
  }

  /** Get prompt formatted for Cursor & Windsurf (@codebase style) */
  getCursorPrompt(): string {
    const mem = this.memoryManager.get();
    const body = this.compressor.generateMinimizedPrompt(mem);
    const prompt = `@codebase ${mem.project.name} Context:\n${body}`;
    return SecretRedactor.sanitize(prompt);
  }

  /** Calculate estimated dollar savings ($) based on token reduction */
  calculateDollarSavings(): { savedTokens: number; dollarSavings: string } {
    const mem = this.memoryManager.get();
    const original = mem.meta.tokenEstimate.original || 0;
    const compressed = mem.meta.tokenEstimate.compressed || 0;
    const savedTokens = Math.max(0, original - compressed);

    // Standard LLM input token price: ~$3.00 per 1 million tokens ($0.000003 per token)
    const costPerToken = 0.000003;
    const dollars = (savedTokens * costPerToken).toFixed(2);

    return {
      savedTokens,
      dollarSavings: `$${dollars}`
    };
  }

  /** Get just the prompt text without writing to file */
  getPromptText(): string {
    const mem = this.memoryManager.get();
    return HEADER + this.compressor.generateOptimizedPrompt(mem);
  }
}
