import * as path from 'path';
import { MemoryManager } from '../core/MemoryManager';
import { ContextCompressor } from '../core/ContextCompressor';
import { writeTextFile } from '../utils/fileUtils';

const HEADER = `# ═══════════════════════════════════════════════════════════
# OPTIMIZED AI CONTEXT PROMPT — Generated by Context Optimizer
# Compatible with: ChatGPT, Claude, Gemini, Cursor, Windsurf,
#                  GitHub Copilot, Antigravity, and any LLM
# ═══════════════════════════════════════════════════════════
# INSTRUCTIONS FOR AI:
# Read this context carefully. This is a complete snapshot of
# the project. Use it to understand the codebase without
# needing additional explanation.
# ═══════════════════════════════════════════════════════════

`;

export class PromptExporter {
  constructor(
    private memoryManager: MemoryManager,
    private compressor: ContextCompressor
  ) {}

  /** Export the full, readable optimized prompt */
  exportFull(): string {
    const mem = this.memoryManager.get();
    const content = HEADER + this.compressor.generateOptimizedPrompt(mem);
    const outputPath = path.join(this.memoryManager.getExportsDir(), 'optimized_prompt.txt');
    writeTextFile(outputPath, content);
    return outputPath;
  }

  /** Export the minimized (lowest token) prompt */
  exportMinimized(): string {
    const mem = this.memoryManager.get();
    const content = this.compressor.generateMinimizedPrompt(mem);
    const outputPath = path.join(this.memoryManager.getExportsDir(), 'optimized_prompt.min.txt');
    writeTextFile(outputPath, content);
    return outputPath;
  }

  /** Get just the prompt text without writing to file */
  getPromptText(): string {
    const mem = this.memoryManager.get();
    return HEADER + this.compressor.generateOptimizedPrompt(mem);
  }
}
